<template>
  <v-dialog>
    <v-card>
      <v-card-title>Add Asset Type</v-card-title>
      <v-card-text>
        <v-list>
          <v-item-list>
            Asset Type
            <v-list-item-action>
              <v-text-field></v-text-field>
            </v-list-item-action>
          </v-item-list>
          <v-item-list>Asset Delivery Date</v-item-list>
          <v-item-list>Asset Cost</v-item-list>
          <v-item-list>Refresh Date</v-item-list>
          <v-item-list>Asset Project</v-item-list>
        </v-list>
      </v-card-text>
    </v-card>
  </v-dialog>
</template>

<script>
export default {};
</script>

<style>
</style>